# Generated by Django 4.2 on 2026-05-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('M', 'Miedo'), ('AC', 'Accion'), ('TR', 'Triller'), ('R', 'Romance'), ('MU', 'Musical'), ('C', 'Comedia'), ('F', 'Filosofico'), ('NA', 'No Definida')], default='NA', max_length=2)),
                ('director', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('synopsis', models.TextField(null=True)),
            ],
        ),
    ]
